### PR TITLE
Buttons

### PR DESCRIPTION
**Pull request by sashako**
screen shot 2017-02-01 at 2 30 07 pm
screen shot 2017-02-01 at 2 28 48 pm
screen shot 2017-02-01 at 2 30 25 pm

Also includes:
+ partials support for docs
+ downgrading normalize. Normalize 5.0 overrides some font styling

### CODE REVIEW

**Comment by soulware** [comment]
First button should be `large` and not `small`?

**Comment by sashako** [comment]
@soulware, good catch!

**Comment by nhinsch** [comment]
Design issue: can we add colored disabled states to the colored buttons? I recently added this to Quiche.

**Comment by sashako** [comment]
@nhinsch discussed with Alex and JT, for your case, we would use loading states. Disabled states will remain gray. When we want to disable a button when an API call is happening, loading state is appropriate. The styles that you added, won't be there once the new styleguide is ported over

**Comment by nhinsch** [comment]
OK that will be fine, as long as the loading state blocks the user from clicking the button a second time. Looks great!

**Comment by sashako** [comment]
@nhinsch it does

**Comment by nhinsch** [comment]
Also, is there a reason we use `cursor: not-allowed` on disabled buttons? I haven't noticed this on other sites.

**Comment by sashako** [comment]
no reason. nice indication that you can't click the button. we can use something else that's not a pointer

**Comment by nhinsch** [comment]
Sounds good. Let's ask JT. It seems most sites just use the default cursor.

**Pull request merged**
