### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by binay-poudel**

### CODE REVIEW

**Comment by nhinsch** [comment]
I think this should actually be 1.8.10, right?

**Comment by nhinsch** [comment]
http://semver.org/

**Comment by binay-poudel** [comment]
https://github.com/managedbyq/juice/releases?after=1.8.0
We are not using that I think.

**Comment by nhinsch** [comment]
I think all npm packages are supposed to use it. 
https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by binay-poudel** [comment]
Yeah that makes sense.

**Pull request merged**
