### PR TITLE
add horizontal dots icon

### PR DESCRIPTION
**Pull request by SamHerbert**
Describe your changes here. Please remember that this description will be publicly visible.

### CODE REVIEW

**Comment by nhinsch** [comment]
What does this icon look like? Should it be called "ellipsis"?

**Comment by SamHerbert** [comment]
screen shot 2019-03-08 at 12 10 07 pm
@nhinsch It could be called that. We may have a version where they are vertical. Currently, quiche has a component where they are referred to as `kebab` and `meatball` (hard coded). I felt like this was a cleaner name.

**Comment by nhinsch** [comment]
Hahaha "meatball"

**Comment by kyythane** [comment]
I don't like ellipsis because an ellipsis is a specific glyph in text

**Pull request merged**
